- name: render eni
  template:
    src: "eni.j2"
    dest: /etc/network/interfaces

- name: activate interfaces
  shell:  /sbin/ifreload -a

- name: render frr
  template:
    src: "frr.j2"
    dest: /etc/frr/ffr.conf

- name: activiere routing
  service: name=frr state=restarted
