#!/bin/bash

# ALQ, Wittdün 2022
# chmod
# ./prepare

# problem $HOME wird das Ursprungs-Home sein...

PFAD="$HOME/ON-01/preparation"
WARNUNG='Please verify if nginx is correctly configured (tested on leaf11 for all) and up & running'

# ruft jetzt die scripte unter ~/ON-01/preparation auf

echo "STEP-01: runnig ownership to fix format and owner"

sudo bash "$PFAD/ownership"

echo
echo "STEP-02: running script to prepare NVUE API Access"
echo

sudo ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts $PFAD/api_file.yaml

echo "nach dem playbook api_file"

erg=$(curl  -u 'cumulus:CumulusLinux!' --insecure https://192.168.200.2:8765/cue_v1/interface)
echo "$erg"

if [[ $erg == *"Authorization Required"* ]]; then
  echo $WARNUNG
fi

curl -u 'cumulus:CumulusLinux!' --insecure https://192.168.200.2:8765/cue_v1/interface

# Zum Testen

#erg=$(curl  -u 'cumulus:BadPassword' --insecure https://192.168.200.2:8765/cue_v1/interface)

#if [[ $erg == *"Authorization Required"* ]]; then
#  echo $WARNUNG
#fi

exit 0
