#!/bin/bash
# ex:ts=4:sw=4:sts=4:et
# -*- tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-

# ALQ, Hamburg 2023
# 
# sudo ./r_unit-40

if [ -f /home/cumulus/ON-01/additional.conf ]; then
        . /home/cumulus/ON-01/additional.conf
fi

# ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./cleanup/main.yaml
# ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-40/main.yaml

clear

echo "*************** description *********************************************************"
echo "*                                                                                   *"
echo "*  configuring for unit-40 pure L3-Fabric                                           *"
echo "*  To do : FRR installation on hosts                                                *"
echo "*                                                                                   *"
echo "******************* end *************************************************************"


PS3='Please enter your choice: '
options=("Switches" "Host-Config" "Quit")
select opt in "${options[@]}"
do
    case $opt in
         "Switches")
            echo "CL 4 and CL 5 setup"
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-40/main.yaml
            break
            ;;
         "Host-Config")
            echo "Copy Daemons and Config to Hosts"
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-40/main-host.yaml
            break
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
