#!/bin/bash
# ex:ts=4:sw=4:sts=4:et
# -*- tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-

# ALQ, Hamburg 2023
# 
# sudo ./r_unit-04_flexible_snippet

if [ -f /home/cumulus/ON-01/.additional.conf ]; then
        . /home/cumulus/ON-01/.additional.conf
fi

echo
echo "********** description *******************"
echo "*                                        *"
echo "* preparing the CL 5.x nodes for         *"
echo "* an optional hands-on excersise         *"
echo "*                                        *"
echo "*                                        *"
echo "*                                        *"
echo "************** end ***********************"
echo
echo "********************************* description ********************************************************"
echo "*                                                                                                    *"
echo "* copied motd.sh to your profile                                                                     *"
echo "*                                                                                                    *"
echo "* cumulus@leaf11:mgmt:~$ cat fs.yaml                                                                 *"
echo "* - set:                                                                                             *"
echo "*   system:                                                                                          *"
echo "*      config:                                                                                       *"
echo "*        snippet:                                                                                    *"
echo "*          motd-flexible-snippet:                                                                    *"
echo "*            content: |                                                                              *"
echo "*              # Adding a line                                                                       *"
echo "*              echo "<customer name> 2023"                                                           *"
echo "*            file: /etc/profile.d/motd.sh                                                            *"
echo "*                                                                                                    *"
echo "************************************* end ************************************************************"
echo
echo 
PS3='Please enter your choice: '
options=("copy motd" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "copy motd")
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-04/main.yaml
            break
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
