#!/bin/bash
# ex:ts=4:sw=4:sts=4:et
# -*- tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-

# ALQ, Wittdün 2022
# 
# sudo ./r_unit-03

if [ -f /home/cumulus/ON-01/additional.conf ]; then
        . /home/cumulus/ON-01/additional.conf
fi

echo
echo

PS3='Please enter your choice: '
options=("Final state of unit-03" "Quit")
select opt in "${options[@]}"

do
    case $opt in
         "Final state of unit-03")
            echo
            echo "moving to end of unit-03 taks"
            echo "configuring host11 and host22"
            echo "configuring router01 and router02"
            echo "configuring customer01"
            echo
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-03-role/playbooks/main.yaml
            break
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done

exit 0


