#!/bin/bash
# ex:ts=4:sw=4:sts=4:et
# -*- tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-

# ALQ, Wittdün 2022
# 
# sudo ./r_unit-06

if [ -f /home/cumulus/ON-01/additional.conf ]; then
        . /home/cumulus/ON-01/additional.conf
fi

echo
echo "configuring for unit-06 MLAG"
echo "creating L2 end-to-end connectivity"
echo
echo "expected outcome 01: host11 (172.16.10.1) can reach host22 (172.16.10.2)"
echo "expected outcome 02: MLAG is setup"
echo "expected outcome 03: restriction and optional steps are satisfied"
echo

PS3='Please enter your choice: '
options=("move to end of first task of unit-06" "base setup" "base without MLAG" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "move to end of first task of unit-06")
            echo "working without redundancy..."
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-06-role/playbooks/main.yaml
            # set if down
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-06-role/playbooks/s24.yaml
            # set filter
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-06-role/playbooks/s23.yaml
            break
            ;;   
        "base setup")
            echo "configuring base setup for troubleshooting"
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-06-role/playbooks/main.yaml
            break
            ;;
        "base without MLAG")
            echo "hands-on leaf11/12/21/22"
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-06-role/playbooks/main.yaml
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-06-role/playbooks/l11.yaml
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-06-role/playbooks/l21.yaml
            break
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
