#!/bin/bash
# ex:ts=4:sw=4:sts=4:et
# -*- tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-

# ALQ, Wittdün 2022
# 
# sudo ./r_unit-05

if [ -f /home/cumulus/ON-01/.additional.conf ]; then
        . /home/cumulus/ON-01/.additional.conf
fi


echo "*************** description *********************************************************"
echo "*                                                                                   *"
echo "* configuring for unit-08 BGP unnumbered                                            *"
echo "* creating L3 end-to-end connectivity                                               *"
echo "*                                                                                   *"
echo "* expected outcome 01: announcing all loopbacks                                     *"
echo "* however, host11 can not or no longer reach host22                                 *"
echo "* both hosts in the same broadcast domain                                           *"
echo "* are seperated by a layer 3 data center fabric                                     *"
echo "*                                                                                   *"
echo "*                                                                                   *"
echo "******************* end *************************************************************"

PS3='Please enter your choice: '
options=("move to final unit status" "hands-on leaf11" "hands-on leaf11 and spine13" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "move to final unit status")
            echo "configuring final status"
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-08-role/playbooks/main.yaml
            break
            ;;
        "hands-on leaf11")
            echo "hands-on leaf11"
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-08-role/playbooks/main.yaml
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-08-role/playbooks/l11.yaml
            break
            ;;
        "hands-on leaf11 and spine13")
            echo "you chose choice hands-on leaf11 and spine13"
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-08-role/playbooks/main.yaml
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-08-role/playbooks/l11.yaml
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-08-role/playbooks/s13.yaml
            break
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
