#!/bin/bash
# ex:ts=4:sw=4:sts=4:et
# -*- tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-

# ALQ, Wittdün 2022
# 
# sudo ./r_unit-10

if [ -f /home/cumulus/ON-01/.additional.conf ]; then
        . /home/cumulus/ON-01/.additional.conf
fi

echo "*************** description *********************************************************"
echo "*                                                                                   *"
echo "* configuring for unit-10 filter                                                    *"
echo "* creating forward-looking infrastructure based on unit-12 EVPN-L2                  *"
echo "*                                                                                   *"
echo "*                                                                                   *"
echo "*                                                                                   *"
echo "******************* end *************************************************************"
echo "===         description            ==="
echo

echo

PS3='Please enter your choice: '
options=("hands-on" "after part A" "Quit")
select opt in "${options[@]}"
do
    case $opt in
         "hands-on")
            echo "configuring the starting point to practice"
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-10-role/playbooks/main.yaml
            break
            ;;
        "after part A")
            echo "configuring final status"
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-10-role/playbooks/main.yaml
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-10-role/playbooks/spine.yaml
            break
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
