#!/bin/bash
# ex:ts=4:sw=4:sts=4:et
# -*- tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-

# ALQ, Hamburg 2022
# 
# sudo ./r_unit-11

if [ -f /home/cumulus/ON-01/.additional.conf ]; then
        . /home/cumulus/ON-01/.additional.conf
fi
echo "===         description            ==="
echo
echo
echo "configuring for unit-11 tunnel"
echo "Tunnel type vxlan between leaf11 and leaf22"
echo "Control static"
echo "===            end                ==="
echo

PS3='Please enter your choice: '
options=("Final state of unit-11 step-1" "hands-on" "Quit")
select opt in "${options[@]}"
do
    case $opt in
         "Final state of unit-11 step-1")
            echo "the working solution"
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-11-role/playbooks/main.yaml
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-11-role/playbooks/step-1.yaml
            break
            ;;
        "hands-on")
            echo "hands-on Leaf11 and Leaf22"
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-11-role/playbooks/main.yaml
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-10-role/playbooks/L11.yaml
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-10-role/playbooks/L22.yaml
            break
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
