#!/bin/bash
# ex:ts=4:sw=4:sts=4:et
# -*- tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-

# ALQ, Hamburg 2023
# 
# sudo ./r_unit-40

if [ -f /home/cumulus/ON-01/additional.conf ]; then
        . /home/cumulus/ON-01/additional.conf
fi

# ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./cleanup/main.yaml
ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-40/main.yaml

clear

echo "*************** description *Layer 3 setup ******************************************"
echo "*                                                                                   *"
echo "*                                                                                   *"
echo "******************* end *************************************************************"
echo ""
