#!/bin/bash
# ex:ts=4:sw=4:sts=4:et
# -*- tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-

# ALQ, Wittdün 2022
# 
# sudo ./r_unit-10

if [ -f /home/cumulus/ON-01/additional.conf ]; then
        . /home/cumulus/ON-01/additional.conf
fi

echo
echo "configuring for unit-10 filter"
echo "creating forward-looking infrastructure of unit-12 EVPN-L2"
echo
echo

PS3='Please enter your choice: '
options=("start" "move to final unit status" "Quit")
select opt in "${options[@]}"
do
    case $opt in
         "start")
            echo "configuring the starting point"
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-10-role/playbooks/main.yaml
            break
            ;;
        "move to final unit status")
            echo "configuring final status"
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-10-role/playbooks/main.yaml
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-10-role/playbooks/spine.yaml
            break
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
