#!/bin/bash
# ex:ts=4:sw=4:sts=4:et
# -*- tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-

# ALQ, Hamburg 2022
# 
# sudo ./ts_unit_33

if [ -f /home/cumulus/ON-01/additional.conf ]; then
        . /home/cumulus/ON-01/additional.conf
fi

PS3='TS 33| EVPN-L3 Troubleshooting. Please enter your choice: '
options=("EVPN-L3 SYM" "Restore" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "EVPN-L3 SYM")
            echo "Host11 reports connectivity loss to Host22"
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-13-role/playbooks/main.yaml
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-33-ts/main1.yaml
            break
            ;;
        "Restore")
            echo "Fixed"
            ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-13-role/playbooks/main.yaml
            break
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done

clear

echo
echo "****************** description Ticket 33 ********************************************"
echo "*                                                                                   *"
echo "*  Host11 uses 172.16.10.1/24 on bond1                                              *"
echo "*  Host22 uses 172.16.20.2/24 on bond1                                              *"
echo "*  both hosts are multi-homed and are able to ping 'their gw'                       *"
echo "*                                                                                   *"
echo "*                                                                                   *"
echo "******************* end *************************************************************"
echo
echo

echo "****************** goal and useful commands *****************************************"
echo "*                                                                                   *"
echo "*  Host11 should be able to reach host22                                            *"
echo "*  cumulus@leaf11:mgmt:~$ ip route show vrf A1                                      *"
echo "*      172.16.20.2 nhid 100 proto bgp metric 20                                     *"
echo "*                                                                                   *"
echo "*  cumulus@leaf11:mgmt:~$ sudo vtysh -c "show bgp sum"                              *"
echo "*                                                                                   *"
echo "******************* end *************************************************************"
