#!/bin/bash
# ex:ts=4:sw=4:sts=4:et
# -*- tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-

# ALQ, Hamburg 2022
# 
# sudo ./ts_unit_31

if [ -f /home/cumulus/ON-01/additional.conf ]; then
        . /home/cumulus/ON-01/additional.conf
fi

ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./cleanup/main.yaml
ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-07-role/playbooks/main.yaml
ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-31-ts/main.yaml

clear

echo "*************** description *Layer 2 Troubleshooting Ticket 31***********************"
echo "*                                                                                   *"
echo "*  Task based on unit-07 setup with MLAG and L3 interfaces as test points           *"
echo "*                                                                                   *"
echo "*  First test from host22 to reach the ip address of host11 (172.16.10.1)           *"
echo "*  Secondly verify on host11 that bond1 is using 172.16.10.1                        *"
echo "*     cumulus@host11:~$ ip -br a show dev bond1                                     *"
echo "*     bond1            UP             172.16.10.1/24 fe80::48d7:feff:fe78:a299/64   *"
echo "*  Host11 can ping 172.16.10.2 but Host22 (tcpdump: reports no ICMP packets!)       *"
echo "*                                                                                   *"
echo "*                                                                                   *"
echo "*  Host11 can ping the SVI of leaf11 and leaf 12 but neitehr leaf 21 nor leaf 22    *"
echo "*  Host11 can not ping the .254 anycast address                                     *"
echo "*                                                                                   *"
echo "*  there might be more challenges, document, fix, and have fun                      *"
echo "*                                                                                   *"
echo "******************* end *************************************************************"
echo ""
echo "*************** helpful commands ****************************************************"
echo "*                                                                                   *"
echo "*  $ ip -br l                                                                       *"
echo "*  $ ip -br a                                                                       *"
echo "*  $ ip n                                                                           *"
echo "*  $ sudo tcpdump -i <if> icmp                                                      *"
echo "*  $ bridge vlan                                                                    *"
echo "*                                                                                   *"
echo "******************* end *************************************************************"
echo ""
echo "****************** goal *************************************************************"
echo "*                                                                                   *"
echo "*  Host11 should be able to reach:                                                  *"
echo "*                                                                                   *"
echo "*  - host22                                                                         *"
echo "*  - SVI's of leaf11,12,21,and 22                                                   *"
echo "*  - VRR (172.16.10.254)                                                            *"
echo "*                                                                                   *"
echo "******************* end *************************************************************"
