#!/bin/bash
# ex:ts=4:sw=4:sts=4:et
# -*- tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-

# ALQ, Hamburg 2022
# 
# sudo ./ts_unit_31

if [ -f /home/cumulus/ON-01/additional.conf ]; then
        . /home/cumulus/ON-01/additional.conf
fi

ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./cleanup/main.yaml
ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-07-role/playbooks/main.yaml
ansible-playbook -i /home/cumulus/ON-01/inventory/files/hosts ./unit-31-ts/main.yaml

clear

echo "*************** description *********************************************************"
echo "*                                                                                   *"
echo "*  Task based on unit-07                                                            *"
echo "*                                                                                   *"
echo "*  Host11 can ping the SVI of leaf11 and leaf 12 but not of leaf 21 or leaf 22      *"
echo "*  Host11 can not ping the .254 anycast address                                     *"
echo "*  Host11 can ping 172.16.10.2 but Host22 (tcpdump: reports no ICMP packets!)       *"
echo "*  there might be more challenges                                                   *"
echo "*                                                                                   *"
echo "******************* end *************************************************************"
echo ""
