---
- hosts: cumulus-5x-nodes
  become: true
  user: cumulus
  gather_facts: false
      
  roles:
    - /home/cumulus/ON-01/unit-03-role/roles/cl5
    
- hosts: cumulus-4x-nodes
  name: e/n/i
  become: yes
  gather_facts: no
  tasks:
    - name: Interface
      copy:
        src: /home/cumulus/ON-01/unit-03-role/{{ inventory_hostname }}.if
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes for all cumulus nodes
      shell: ifreload -a
           
- hosts: host
  name: netplan
  become: yes
  gather_facts: no
  tasks:
    - name: cloud file entfernen
      ansible.builtin.file:
        path: /etc/netplan/50-cloud-init.yaml
        state: absent
    - name: cloud file entfernen
      ansible.builtin.file:
        path: /etc/netplan/config.yaml
        state: absent
    - name: copy netplan yaml
      copy:
        src: /home/cumulus/ON-01/unit-03-role/{{ inventory_hostname }}.yaml
        dest: /etc/netplan/config.yaml
    - name: apply netplan yaml
      shell: netplan apply
       
    - name: Check interface 2
      shell: /sbin/ip -br -4 a | grep 'bond'
      ignore_errors: yes
      register: result
    - debug: msg={{ result.stdout }}
