-
  name: prepare oob-mgmt-server
  hosts: localhost
  tasks:
   -  name: test
      ansible.builtin.user:
        name: cumulus1
        shell: /bin/bash
        groups: cumulus
        append: yes
        
   -  name: test-2
      shell: usermod -aG sudo cumulus1
      args:
        executable: /bin/bash
      
- hosts: localhost
  become: true
  user: ubuntu
  gather_facts: false
  
  tasks:
    - name: add cumulus user
      user: 
      name: cumulus  
      group: admin
      shell: /bin/bash
      comment: "admin user"
      password: "$6$alq$WRoBPYvpxl0kxnfgcCB6SZ1MxRmBV8/aHhwGAOn17fp8pszaAsVzxy7qPUBHX71ovin1epXCbleKgiUcqlrzT1"   
