- 
  hosts: localhost
  become: true
  user: ubuntu
  gather_facts: false

  tasks:
    - name: add cumulus user
      ansible.builtin.user: 
        name: cumulus4
        group: admin
        shell: /bin/bash
        comment: "admin user"
        password: "$6$alq$WRoBPYvpxl0kxnfgcCB6SZ1MxRmBV8/aHhwGAOn17fp8pszaAsVzxy7qPUBHX71ovin1epXCbleKgiUcqlrzT1"  
        
    - name create dir
      ansible.builtin.file:
      path: /home/cumulus4/.ssh
      state: directory
      mode: '0755'
      
    - name set dir ownership
      ansible.buildin.file:
      path: /home/cumulus4/.ssh
      state: directory
      recurese: yes
      owner: cumulus4
      group: admin
      
    - name: copy dir    
      ansible.builtin.copy:
        src: /home/ubuntu/.ssh/
        dest: /home/cumulus4/.ssh/
        owner: cumulus4
        group: admin
        mode: u+rwx

