-
  name: prepare oob-mgmt-server
  hosts: localhost
  tasks:
   -  name: test
      ansible.builtin.user:
        name: cumulus1
        shell: /bin/bash
        groups: cumulus
        append: yes
        
   -  name: test-2
      shell: usermod -aG sudo cumulus1
      args:
        executable: /bin/bash
      
