- hosts: leaf11 leaf21
  name: startup
  become: yes
  gather_facts: no
  ignore_errors: yes
  tasks:
    - name: unit-11 Tunnel step-1
      copy:
        src: /home/cumulus/ON-01/unit-11-role/playbooks/{{ inventory_hostname }}-step-1.yaml
        dest: /etc/nvue.d/startup.yaml
    # aktivieren
    - name: activate changes for all cumulus nodes
      shell:  nv config apply startup -y
