- hosts: leaf11 leaf22
  name: startup
  become: yes
  gather_facts: no
  ignore_errors: yes
  tasks:
    - name: unit-11 Tunnel step-2
      copy:
        src: /home/cumulus/ON-01/unit-11-role/{{ inventory_hostname }}-step-2.yaml
        dest: /etc/nvue.d/startup.yaml
    # aktivieren
    - name: activate changes for all cumulus nodes
      shell:  nv config apply startup -y
