- hosts: leaf11 leaf12 leaf21 leaf22 spine13 spine14 spine23 spine24
  name: e/n/i
  become: yes
  gather_facts: no
  tasks:
    - name: unit-34-ts 
      copy:
        src: /home/cumulus/ON-01/unit-34-ts/{{ inventory_hostname }}.yaml
        dest: /etc/nvue.d/startup.yaml
    # aktivieren
    - name: activate changes 
      shell: nv config apply startup
