- hosts: customer01
  name: e/n/i
  become: yes
  gather_facts: no
  tasks:
    - name: Interface
      copy:
        src: /home/cumulus/ON-01/unit-05-role/{{ inventory_hostname }}.if
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes for all cumulus nodes
      shell: ifreload -a
