- hosts: wan02
  name: startup
  become: yes
  gather_facts: no
  ignore_errors: yes
  tasks:
    - name: unit-05 
      copy:
        src: /home/cumulus/ON-01/unit-05-role/playbooks/{{ inventory_hostname }}.yaml
        dest: /etc/nvue.d/startup.yaml
    # aktivieren
    - name: activate changes for all cumulus nodes
      shell:  nv config apply startup -y
