- hosts: leaf11 
  name: e/n/i
  become: yes
  gather_facts: no
  tasks:
    - name: unit-35-ts 
      copy:
        src: /home/cumulus/ON-01/unit-35-ts/{{ inventory_hostname }}.yaml
        dest: /etc/nvue.d/startup.yaml
    # aktivieren
    - name: activate changes 
      shell: nv config apply startup

- hosts: host
  name: netplan
  become: yes
  gather_facts: no
  tasks:
    - name: cloud file entfernen
      ansible.builtin.file:
        path: /etc/netplan/50-cloud-init.yaml
        state: absent
    - name: cloud file entfernen
      ansible.builtin.file:
        path: /etc/netplan/config.yaml
        state: absent
    - name: copy netplan yaml
      copy:
        src: /home/cumulus/ON-01/unit-53-ts/{{ inventory_hostname }}.yaml
        dest: /etc/netplan/config.yaml
    - name: apply netplan yaml
      shell: netplan apply
       
    - name: Check interface 2
      shell: /sbin/ip -br l | grep 'eth1'
      ignore_errors: yes
      register: result
    - debug: msg={{ result.stdout }}
    
    - name: bounce
      shell: reboot
      ignore_errors: yes
    
