- hosts: host
  name: frr config
  become: yes
  gather_facts: no
  tasks:    
    - name: step-01
      shell: "curl -s https://deb.frrouting.org/frr/keys.asc | sudo apt-key add -"

    - name: step-02
      shell: "echo deb https://deb.frrouting.org/frr focal frr-stable | sudo tee -a /etc/apt/sources.list.d/frr.list"
      
    - name: step-03      
      shell: "apt update && sudo apt install frr frr-pythontools -y"
