---
# MOTD
- hosts: cumulus-5x-nodes
  name: rocket turtle forever
  become: yes
  gather_facts: no
  tasks:
    - name: copy motd 
      copy:
        src: /home/cumulus/ON-01/inventory/files/motd.sh
        dest: /etc/profile.d
        
- hosts: leaf11 leaf12 leaf21 leaf22 spine13 spine14 spine23 spine24
  name: startup L3-Fabric
  become: yes
  gather_facts: no
  tasks:
    - name: unit-40 
      copy:
        src: /home/cumulus/ON-01/unit-40/{{ inventory_hostname }}.yaml
        dest: /etc/nvue.d/startup.yaml
    # aktivieren
    - name: activate changes 
      shell: nv config apply startup -y
        
# ENI, Daemons und FRR    
- hosts: cumulus-4x-nodes
  name: e/n/i daemons und frr
  become: yes
  gather_facts: no
  tasks:
        
    - name: Daemons
      copy:
        src: /home/cumulus/ON-01/unit-40/daemons
        dest: /etc/frr/daemons
        
    # aktivieren
    - name: activate changes for all cumulus nodes
      shell: systemctl restart frr
      
    - name: Interface
      copy:
        src: /home/cumulus/ON-01/unit-40/{{ inventory_hostname }}.eni
        dest: /etc/network/interfaces
        
    # aktivieren
    - name: activate changes for all cumulus nodes
      shell: ifreload -a
      
    - name: FRR config
      copy:
        src: /home/cumulus/ON-01/unit-40/{{ inventory_hostname }}.frr
        dest: /etc/frr/frr.conf
    # aktivieren
    - name: activate changes for all cumulus nodes
      shell: systemctl reload frr
