- hosts: host
  name: frr config
  become: yes
  gather_facts: no
  tasks:
    - name: copy daemons
      copy:
        src: /home/cumulus/ON-01/unit-40/dh
        dest: /etc/frr/daemons
        
    - name: copy frr
      copy:
        src: /home/cumulus/ON-01/unit-40/{{ inventory_hostname }}.frr
        dest: /etc/frr/frr.conf      
        
    - name: apply 
      shell: sudo systemctl restart frr
      
