---
- hosts: leaf
#  strategy: free
  become: true
  user: cumulus
  gather_facts: false
      
  roles:
    - /home/cumulus/ON-01/unit-07-role/roles/leaf_l3if
    - /home/cumulus/ON-01/unit-07-role/roles/leaf_l3if_patch
    - /home/cumulus/ON-01/unit-07-role/roles/vrf_light_patch
  
- hosts: spine
  strategy: free
  become: true
  user: cumulus
  gather_facts: false
      
  roles:
    - /home/cumulus/ON-01/unit-07-role/roles/spine_l3if
     
- hosts: host
  strategy: free
  become: true
  user: cumulus
  gather_facts: false
  tasks:
    - name: copy netplan yaml
      copy:
        src: /home/cumulus/ON-01/inventory/files/{{ inventory_hostname }}-unit-07-l3if
        dest: /etc/netplan/config.yaml
    - name: apply netplan yaml
      shell: netplan apply
      
- hosts: router01      
  become: true
  user: cumulus
  gather_facts: false
  
  tasks:
    - name: ip link
      shell: ip link {{ item }}
      with_items:
      - add A type vrf table 1002
      - add B type vrf table 1003
      - add C type vrf table 1004
      - add name swp1.20 link swp1 type vlan id 20
      - add name swp1.21 link swp1 type vlan id 21
      - add name swp1.22 link swp1 type vlan id 22
      - set dev swp1 up
      - set dev A up
      - set dev B up
      - set dev C up
      - set dev swp1.20 master A
      - set dev swp1.21 master B
      - set dev swp1.22 master C
    - name: ip address
      shell: ip address add {{ item }}
      with_items: 
      - 172.16.20.1/30 dev swp1.20
      - 172.16.21.1/30 dev swp1.21
      - 172.16.22.1/30 dev swp1.22

- hosts: router02
  name: prepare router02
  become: yes
  gather_facts: no
  tasks:
    - name: e/n/i file and interface manager activation
      copy:
        src: /home/cumulus/ON-01/inventory/files/router02.if
        dest: /etc/network/interfaces
    # ifreload
    - name: activate changes 
      shell: /sbin/ifreload -a


# gewechselt auf j2 mit einer eigenen role

#- hosts: leaf
#  become: true
#  user: cumulus
#  gather_facts: false
#  tasks:
#    - name: patch vrf and sub-interfaces
#      copy:
#        src: /home/cumulus/ON-01/unit-07-role/playbooks/{{inventory_hostname}}_patch
#        dest: /etc/nvue.d/{{inventory_hostname}}_patch.yaml
#    
#    - name: patch changes
#      shell: nv config patch /etc/nvue.d/{{inventory_hostname}}_patch.yaml
#      
#    - name: activate changes
#      shell: nv config apply startup
