---
- hosts: leaf
  become: true
  user: cumulus
  gather_facts: false
      
  roles:
    - /home/cumulus/ON-01/unit-07-role/roles/leaf_l3if
    
- hosts: spine
  become: true
  user: cumulus
  gather_facts: false
      
  roles:
    - /home/cumulus/ON-01/unit-07-role/roles/spine_l3if
     
- hosts: host
  become: true
  user: cumulus
  gather_facts: false
  tasks:
    - name: copy netplan yaml
      copy:
        src: /home/cumulus/ON-01/inventory/files/{{ inventory_hostname }}-unit-07-l3if
        dest: /etc/netplan/config.yaml
    - name: apply netplan yaml
      shell: netplan apply
