- name: render patch 
  template:
    src: "l3if_patch.j2"
    dest: /tmp/patch.yaml
    
- name: patch
  shell: nv config patch /tmp/patch.yaml
    
#- name: activate changes
#  shell:  nv config apply -y
