- hosts: leaf
#  strategy: free
  become: true
  user: cumulus
  gather_facts: false
      
  roles:
    - /home/cumulus/ON-01/unit-12-role/roles/leaf

- hosts: spine
  strategy: free
  become: true
  user: cumulus
  gather_facts: false
      
  roles:
    - /home/cumulus/ON-01/unit-12-role/roles/spine


# done NOV fixed bond
- hosts: host
  become: true
  user: cumulus
  gather_facts: false
  tasks:
    - name: copy netplan yaml
      copy:
        src: /home/cumulus/ON-01/inventory/files/{{ inventory_hostname }}-unit-12
        dest: /etc/netplan/config.yaml
    - name: apply netplan yaml
      shell: netplan apply
      
      
# done NOV fixed bond
- hosts: host
  become: true
  user: cumulus
  gather_facts: false
  tasks:
    - name: copy netplan yaml
      copy:
        src: /home/cumulus/ON-01/inventory/files/{{ inventory_hostname }}-unit-06-mlag
        dest: /etc/netplan/config.yaml
    - name: apply netplan yaml
      shell: netplan apply
