- hosts: cumulus-5x-nodes
  name: startup
  become: yes
  gather_facts: no
  ignore_errors: yes
  tasks:
    - name: cp api_file
      copy:
        src: /home/cumulus/ON-01/prepare/api_file
        dest: /home/cumulus
    - name: run it
      shell: sudo bash /home/cumulus/api_file
