#!/bin/bash

# ALQ, Wittdün 2022

# Vorbereiten für NVUE API 
# auf den CL5.x Geräten

sudo ln -s /etc/nginx/sites-{available,enabled}/nvue.conf
sudo sed -i 's/listen localhost:8765 ssl;/listen 0.0.0.0:8765 ssl;/g' /etc/nginx/sites-available/nvue.conf
sudo systemctl restart nginx
