- hosts: spine
  name: startup
  become: yes
  gather_facts: no
  ignore_errors: yes
  tasks:
    - name: unit-10
      copy:
        src: /home/cumulus/ON-01/unit-10-role/playbooks/{{ inventory_hostname }}.yaml
        dest: /etc/nvue.d/startup.yaml
    # aktivieren
    - name: activate changes for all spine nodes
      shell:  nv config apply startup -y
