- hosts: leaf
#  strategy: free
  become: true
  user: cumulus
  gather_facts: false
      
  roles:
    - /home/cumulus/ON-01/unit-13-role/roles/leaf

- hosts: spine
  strategy: free
  become: true
  user: cumulus
  gather_facts: false
      
  roles:
    - /home/cumulus/ON-01/unit-13-role/roles/spine

- hosts: host22
  name: netplan
  become: yes
  gather_facts: no
  tasks:
    - name: copy netplan yaml
      copy:
        src: /home/cumulus/ON-01/unit-13-role/{{ inventory_hostname }}.yaml
        dest: /etc/netplan/config.yaml
    - name: apply netplan yaml
      shell: netplan apply
