- hosts: leaf
#  strategy: free
  become: true
  user: cumulus
  gather_facts: false
      
  roles:
    - /home/cumulus/ON-01/unit-10-role/roles/leaf

- hosts: spine
  strategy: free
  become: true
  user: cumulus
  gather_facts: false
      
  roles:
    - /home/cumulus/ON-01/unit-10-role/roles/spine

- hosts: wan
  strategy: free
  become: true
  user: cumulus
  gather_facts: false
      
  roles:
    - /home/cumulus/ON-01/unit-10-role/roles/wan

- hosts: host
  become: true
  user: cumulus
  gather_facts: false
  tasks:
    - name: copy netplan yaml
      copy:
        src: /home/cumulus/ON-01/inventory/files/{{ inventory_hostname }}-unit-05
        dest: /etc/netplan/config.yaml
    - name: apply netplan yaml
      shell: netplan apply
